- name : Error handling
  hosts: local
  connection: local
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id roboshop
    register: user_output

  - name: print the user_output
    ansible.builtin.debug:
     msg: "{{ user_output }}"