- name: ansible facts
  connection: local
  hosts: local
  vars:
  tasks:
   - name: check redhat or not
     ansible.builtin.debug:
       msg: "yes Package family is redhat"
     when: ansible_facts.os_family == "RedHat"

   - name: check Debian or not
     ansible.builtin.debug:
       msg: "yes Package family is Debian"
     when: ansible_facts.os_family == "Debian"
