- name: command vs shell module
  connection: local
  hosts: local
  tasks:
  - name: command module test
    ansible.builtin.command: cat /etc/passwd | grep root
    # ansible.builtin.shell: cat/etc/passwd | grep root
    register: USERS_OUTPUT
    